### ISSUE TITLE
Setup testing & default config for Laravel Collections

### ISSUE THREAD

**Issue by nmokkenstorm** [Sustainabil-IT/phpstan-higher-order-collections#5]
This project started out as part of a different project, which uses Laravel style Collections for a lot of things. This plugin is set up to work with anything that loosely implements the expected functionality, for general usage it would probably be best to work with `illuminate/collection` out of the box.

## todo:

- [x]    Add illuminate/collection as a dev-dependency and suggested package
- [x]    Double check stub files for the necessary template variables
- [x]    Change default plugin configuration to match
- [x]    Add readme.md instructions on how to configure this for different Collection implementations

**Comment by szepeviktor** [comment]
Could you make the above list a "task list"?

- [x]    Add illuminate/collection as a dev-dependency and suggested package
- [x]    Double check stub files for the necessary template variables
- [x]    Change default plugin configuration to match
- [x]    Add readme.md instructions on how to configure this for different Collection implementations
